# Site settings
title: building.are.na
email: info@are.na
description: > # this means to ignore newlines until "baseurl:"
  Building are.na
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://localhost:4000/" # the base hostname & protocol for your site
twitter_username: aredotna
github_username:  arenahq

# Build settings
markdown: kramdown
