# Site settings
title: blog.are.na
email: everyone@are.na
description: > # this means to ignore newlines until "baseurl:"
  Building are.na
url: "http://blog.are.na" # the base hostname & protocol for your site
twitter_username: aredotna
github_username:  arenahq

# Build settings
markdown: kramdown
