# Site settings
title: Are.na / Blog
email: everyone@are.na
description: > # this means to ignore newlines until "baseurl:"
  Building are.na
url: "http://posts.are.na" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

gems: